### ISSUE TITLE
Cunning and Intellect values need to be swapped

### ISSUE THREAD

**Issue by DrainSmith** [ytterbium/genesys-adversary-generator#1]
Sam Gregor-Stewart confirmed in an interview and later in text on the Facebook group that the printed values in the EPG for Intellect and Cunning should be swapped on Table II.2-1: Characteristic Arrays (page 75).

https://www.facebook.com/groups/GenesysRPG/posts/478396859544300
https://s305.podbean.com/pb/501ebc6d8db083c5c24d19f02869fdb0/61951f39/data1/fs89/5474977/uploads/The_Forge_Episode-013.mp3

**Comment by ytterbium** [comment]
Thanks for raising the issue, this table always looked strange to me, but I did not have seen your sources.

It is now corrected in this project with b93e4bfd05f842c1e7b0f1386e835a1d76641829.
